# Generated by Django 4.1.2 on 2023-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valoracion',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
