# Generated by Django 4.1.2 on 2023-07-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_carrito_precio_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
