# Generated by Django 4.1.2 on 2023-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
    ]
