# Generated by Django 4.1.2 on 2023-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_blog_alter_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/static/images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=models.TextField(max_length=2500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/static/images', verbose_name='Imagen'),
        ),
    ]
