# Generated by Django 4.1.2 on 2023-07-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_blog_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
