# Generated by Django 4.1.2 on 2023-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_delete_carrito_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=2500, verbose_name='Descripcion'),
        ),
    ]
